sudo: false

language: node_js

node_js:
  - '8'

before_script:
  - npm run build

script:
  - npm run lint
  - npm test

after_success:
  - openssl aes-256-cbc -K $encrypted_0e70068955a5_key -iv $encrypted_0e70068955a5_iv -in .travis_rsa.enc -out ./.travis_rsa -d
  - chmod 600 $HOME/.ssh/id_rsa
  - .bin/travis-deploy.sh
